### ISSUE TITLE
HTTP API requests return unstable results

### ISSUE THREAD

**Issue by logineimer** [rabbitmq/cluster-operator#492] opened 2020-11-24 14:12 UTC
## Describe the bug
I have a RabbitMQCluster with three replicas. Performing multiple HTTP requests against RabbitMQ API yields unstable results like that:

```
> auth=user:password (base64 encoded)
> curl -L -X GET -H "Authorization: Basic $auth" http://rabbit.cluster.example.com:15672/api/vhosts/my-host
curl: (52) Empty reply from server
> ...
curl: (52) Empty reply from server
> ...
{"name":"my-host","description":"","tags":[],"metadata":{"description":"","tags":[]},"tracing":false,"cluster_state":{"rabbit@rabbitmq-server-1.rabbitmq-nodes.rabbitmq":"running","rabbit@rabbitmq-server-2.rabbitmq-nodes.rabbitmq":"running","rabbit@rabbitmq-server-0.rabbitmq-nodes.rabbitmq":"running"}}
> ...
curl: (52) Empty reply from server
> ...
{"name":"my-host","description":"","tags":[],"metadata":{"description":"","tags":[]},"tracing":false,"cluster_state":{"rabbit@rabbitmq-server-1.rabbitmq-nodes.rabbitmq":"running","rabbit@rabbitmq-server-2.rabbitmq-nodes.rabbitmq":"running","rabbit@rabbitmq-server-0.rabbitmq-nodes.rabbitmq":"running"}}
...
```

On the internet i read that a server yielding empty responses is considered unhealthy. Telling from the logs of the replicas the nodes are perfectly healthy, though. In Management UI Nodes are green, too.

## To Reproduce
1. Setup operator 1.1.0
2. Create a RabbitMQCluster with `replicas: 3, service.type: LoadBalancher`
3. Retrieve admin credentials
4. Create a virtual host called 'my-host'
5. Perform HTTP requests as stated above

**Expected behavior**
I expect the HTTP reponses to be stable and never empty.

## Version information
- RabbitMQ: 3.8.9-management
- RabbitMQ Cluster Operator: 1.1.0
- Kubernetes: 1.19.2

**Comment by ChunyiLyu** [comment] 2020-11-24 17:59
@logineimer I cannot reproduce this error following your steps. If you set the log level to `debug` as in [this example](https://github.com/rabbitmq/cluster-operator/blob/main/docs/examples/custom-configuration/rabbitmq.yaml), you should be able to see debug logs that can confirm whether the server has received the request or not (there should be logs about users authenticating). I would recommend checking any intermediate steps: the external IP, forwarding rules, service ...etc.

**Comment by mkuratczyk** [comment] 2020-11-24 18:07
You can also turn on debugging without a cluster restart with our [kubectl plugin](https://github.com/rabbitmq/cluster-operator/blob/main/bin/kubectl-rabbitmq):
```
kubectl rabbitmq debug INSTANCE
```
or just "manually" (it's the same command that the plugin will run):
```
kubectl exec INSTANCE-server-0 -- rabbitmqctl set_log_level debug
```

**Comment by Gsantomaggio** [comment] 2020-11-24 20:27
@logineimer [the debug logs will be useful ](https://github.com/rabbitmq/cluster-operator/issues/492#issuecomment-733146867). 

>Telling from the logs of the replicas the nodes are perfectly healthy ...

I would exclude some DNS problem following the [k8s guide](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) 



you can lookup the service dns name (in my case is `rabbitmq-two` in the namespace `rabbitmq`):
```
# nslookup rabbitmq-two.rabbitmq
Server:         192.168.128.10
Address:        192.168.128.10#53

Name:   rabbitmq-two.rabbitmq.svc.cluster.local
Address: 192.168.166.65
``` 

use the full dns name to execute the same query from the dns-pod, something like:

```
 #  for i in $(seq 1 20); do  curl   -L  -u test:test http://rabbitmq-two.rabbitmq.svc.cluster.local:15672/api/vhosts/my-host && echo "   " && sleep 1; done
{"name":"my-host","description":"","tags":[],"metadata":{"description":"","tags":[]},"tracing":false,"cluster_state":{"rabbit@rabbitmq-two-server-0.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-2.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-1.rabbitmq-two-nodes.rabbitmq":"running"}}
{"name":"my-host","description":"","tags":[],"metadata":{"description":"","tags":[]},"tracing":false,"cluster_state":{"rabbit@rabbitmq-two-server-0.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-2.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-1.rabbitmq-two-nodes.rabbitmq":"running"}}
{"name":"my-host","description":"","tags":[],"metadata":{"description":"","tags":[]},"tracing":false,"cluster_state":{"rabbit@rabbitmq-two-server-0.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-2.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-1.rabbitmq-two-nodes.rabbitmq":"running"}}
{"name":"my-host","description":"","tags":[],"metadata":{"description":"","tags":[]},"tracing":false,"cluster_state":{"rabbit@rabbitmq-two-server-1.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-2.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-0.rabbitmq-two-nodes.rabbitmq":"running"}}
{"name":"my-host","description":"","tags":[],"metadata":{"description":"","tags":[]},"tracing":false,"cluster_state":{"rabbit@rabbitmq-two-server-0.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-2.rabbitmq-two-nodes.rabbitmq":"running","rabbit@rabbitmq-two-server-1.rabbitmq-two-nodes.rabbitmq":"running"}}
{"name":"my-host","description":"","tags":[],"metadata":{"description":"","tags":[]},"tracing":false,"cluster_state":
```
also `traceroute` helps.

**Comment by logineimer** [comment] 2020-11-25 09:01
The DNS tests seem to be successful. When following the log of my three RabbitMQ replicas I see a lot of `connection_closed_with_no_data_received` messages but I reckon those are produced by AQMP.

I curled against the full qualified IP address instead of my example.com Hostname to exclude problems here. The results are the same.

**Comment by Gsantomaggio** [comment] 2020-11-27 10:41
@logineimer I am not able to reproduce the problem, and I'd need more info.

1.  you have to [enable the debug logs ](https://github.com/rabbitmq/cluster-operator/issues/492#issuecomment-733146867) and check if the call actually arrives in one of the nodes during the fail. 
2. if [1] is yes, is there some error? 
3. if [2] is not, the problem can be still on the DNS. 
4. you should execute the `curl` with `-v` to see all the information like:
```
for i in $(seq 1 20); do  curl -v  -L  -u test:test http://10.245.139.82:15672/api/vhosts/ && echo "   " && sleep 1; done                                                                                                        
*   Trying 10.245.139.82...                                                                                                                                                                                                          
* TCP_NODELAY set                                                                                                                                                                                                                    
* Connected to 10.245.139.82 (10.245.139.82) port 15672 (#0)                                                                                                                                                                         
* Server auth using Basic with user 'test'                                                                                                                                                                                           
> GET /api/vhosts/ HTTP/1.1                                                                                                                                                                                                          
> Host: 10.245.139.82:15672                                                                                                                                                                                                          
> Authorization: Basic dGVzdDp0ZXN0                                                                                                                                                                                                  
> User-Agent: curl/7.61.1                                                                                                                                                                                                            
> Accept: */*                                                                                                                                                                                                                        
>                                                                                                                                                                                                                                    
< HTTP/1.1 200 OK                                                                                                                                                                                                                    
< cache-control: no-cache                                                                                                                                                                                                            
< content-length: 229                                                                                                                                                                                                                
< content-security-policy: script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'self'                                                                                                                                        
< content-type: application/json                                                                                                                                                                                                     
< date: Fri, 27 Nov 2020 10:30:46 GMT                                                                                                                                                                                                
< server: Cowboy                                                                                                                                                                                                                     
< vary: accept, accept-encoding, origin                                                                                                                                                                                              
<                                                                                                                                                                                                                                    
* Connection #0 to host 10.245.139.82 left intact                                                                                                                                                                                    
[{"cluster_state":{"rabbit@rabbitmq-bugs-server-0.rabbitmq-bugs-nodes.tgir-s01e08":"running"},"description":"Default virtual host","metadata":{"description":"Default virtual host","tags":[]},"name":"/","tags":[],"tracing":false}]
```
5. Use the actual IP instead of using the DNS name to see if the behaviour is the same
6. Execute the same test for each POD  and use the POI IP to see if it works. 
7. Use the [rabbitmq diagnostic tool](https://www.rabbitmq.com/rabbitmq-diagnostics.8.html)  in each node to see if everything is ok.


Thank you

**Comment by Gsantomaggio** [comment] 2020-12-09 11:55
We are going to close the issue, let us know in case you still have problems.

**Closed by Gsantomaggio** 2020-12-09 11:55 UTC
Labels: bug
