### ISSUE TITLE
Operator can't override settings in `/etc/rabbitmq/conf.d`

### ISSUE THREAD

**Issue by mkuratczyk** [rabbitmq/cluster-operator#463] opened 2020-11-12 12:12 UTC
## Describe the bug

RabbitMQ supports the `conf.d` pattern to split the config file into multiple smaller files. Files in the `/etc/rabbitmq/conf.d` directory have precedence over `/etc/rabbitmq/rabbitmq.conf`. `spec.rabbitmq.additionalConfig` property is appended to the base configuration and mounted as `/etc/rabbitmq/rabbitmq.conf`. Therefore, RabbitMQ settings shipped in the image's `conf.d` folder cannot be overridden with `additionalConfig`. It's not a huge issue right now because the images don't use `conf.d` extensively (almost at all in fact) but it might become a problem if the `rabbitmq` image adds a setting that a user will want to change but won't be able to.

For reference:
`rabbitmq` image sets `management_agent.disable_metrics_collector = true` 
`rabbitmq:management` doesn't contain any files in `conf.d`
`tanzu-rabbitmq` contains `default_user.conf` and sets `disk_free_limit.relative`

Based on the approach we take, this could be a breaking change (different StatefulSet structure) so let's discuss before GA what to do about it. Options I see:

1. Do nothing. Currently `conf.d` is hardly used so there is no immediate problem.
2. Simply run `rm -f /etc/rabbitmq/conf.d/*` on startup. Pros: non-breaking, simple. Cons: users may be confused that files they see in the image are not present in a running container
3. Mount our config file as `/etc/rabbitmq/conf.d/zzzzzzz_rabbitmq.conf` so that it's the last file to load. Cons: breaking change, ugly/hacky.
4. Mount our config file as we do right now but create a link `/etc/rabbitmq/conf.d/zzzzzzz_rabbitmq.conf -> /etc/rabbitmq/rabbitmq.conf`. Pros: non-breaking. Cons: hacky, technically could fail (in theory there could be a file loaded later, although unlikely to happen by accident)

**Expected behavior**
Values set in `RabbitmqCluster` should take precedence over values set by the image and the operator's defaults.

**Comment by ChunyiLyu** [comment] 2020-11-12 13:19
Two questions: Is `conf.d` a new format of configuration files that will replace `rabbitmq.conf` and other configuration files in the future? For default user and setting `disk_free_limit`, it possible to do it in `rabbitmq.conf` as well. Is there a particular reason for the tanzu rmq to use `conf.d` for these settings?

**Comment by ChunyiLyu** [comment] 2020-11-12 17:16
Had a discussion with @Zerpet and @mkuratczyk 

We decided to do option 1) Do nothing for now. Mostly considering the fact that `conf.d` is not a well-adopted way in the community, and the tanzu rmq image is setting limited configurations using it at the moment. In the future, once we understand that this is a feature that users would love to have, we will consider adding support for it while keep support `spec.rabbitmq.additionalConfig` to give people the choice and to migrate. I will pull this issue back to icebox.

**Comment by Zerpet** [comment] 2020-12-09 11:13
Perhaps we can close this issue as duplicate of #503 ?

**Comment by ChunyiLyu** [comment] 2021-01-13 11:28
As @Zerpet pointed out. Closing

**Closed by ChunyiLyu** 2021-01-13 11:28 UTC
