### ISSUE TITLE
Rabbitmq cluster-operator extra annotations not taken into consideration

### ISSUE THREAD

**Issue by ZiedBenSaber** [rabbitmq/cluster-operator#961] opened 2022-02-15 11:10 UTC
**Description :** 

Am trying to add extra annotations to our rabbitmq cluster-operator to be able to scrap it's logs like we are doing for every other tool / pod in our k8s cluster, but the following yaml doesn't propagate, nor apply any of the given annotations to the operator's child resources like stated here :
https://www.rabbitmq.com/kubernetes/operator/using-operator.html#labels-annotations

Am I doing it wrong, or is this a potential bug ?
Thanks in advance. 

**Here's the yaml :** 
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  image: docker.registry.company/rabbitmq:3.9.8-management
  imagePullSecrets:
  - name: secret
  replicas: {{ rabbitmq_replicas_number }}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - rabbitmq-cluster
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: {{ rabbitmq_request_cpu }}
      memory: {{ rabbitmq_request_memory }}
    limits:
      cpu: {{ rabbitmq_limit_cpu }}
      memory: {{ rabbitmq_limit_memory }}
  rabbitmq:
    additionalConfig: |
      ## RabbitMQ configuration
      ## Ref: https://github.com/rabbitmq/rabbitmq-server/blob/master/deps/rabbit/docs/rabbitmq.conf.example
      total_memory_available_override_value = "{{ rabbitmq_tmaov }}"
      
      ## Memory-based Flow Control threshold.
      vm_memory_high_watermark.relative = "{{ rabbitmq_vmhwr }}"

      disk_free_limit.absolute = "{{ rabbitmq_dfla }}"

      listeners.tcp.default = "{{ rabbitmq_service_port }}"

      management.tcp.port = "{{ rabbitmq_service_managerPort }}"
      log.console.level = info

      ## Consumer timeout
      ## If a message delivered to a consumer has not been acknowledge before this timer
      ## triggers the channel will be force closed by the broker. This ensure that
      ## faultly consumers that never ack will not hold on to messages indefinitely.
      ## 4 hours in milliseconds
      consumer_timeout = 14400000

      default_vhost = /
      default_user= default_user 
      default_pass = "{{ rabbitmq_password }}"
      default_user_tags.administrator = true
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_shovel_management
      - rabbitmq_shovel
      - rabbitmq_top
      - rabbitmq_prometheus
  override:
    statefulSet:
      spec:
        template:
          metadata:
            annotations:
              co.elastic.logs/enabled: "true" # Using a string here is mandatory
              co.elastic.logs/module: rabbitmq
        volumeClaimTemplates:
          - apiVersion: v1
            kind: PersistentVolumeClaim
            metadata:
              name: persistence
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: {{ rabbitmq_storage }}
              volumeMode: Filesystem
          spec:
            nodeSelector:
              k8s.scaleway.com/pool-name: services
```

**Comment by ChunyiLyu** [comment] 2022-02-22 12:39
@ZiedBenSaber RabbitmqCluster annotations and labels are not populated to pod, which is documented in the doc you've linked to https://www.rabbitmq.com/kubernetes/operator/using-operator.html#labels-annotations (`The Pods do not inherit these labels and/or annotations.`)

You could use the statefulSet override to set labels/annotations to pods, just like what you are doing here. I don't know why it didn't work in your case. I was able to use yaml:

```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  override:
    statefulSet:
      spec:
        template:
          metadata:
            annotations:
              co.elastic.logs/enabled: "true" # Using a string here is mandatory
              co.elastic.logs/module: rabbitmq
```

And saw the `co.elastic.logs` annotation in pod:

```
❯ k get pods rabbitmq-cluster-server-0 -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    co.elastic.logs/enabled: "true"
    co.elastic.logs/module: rabbitmq
    prometheus.io/port: "15692"
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-02-22T12:35:00Z"
```

If you still have the pod available, could you do a `kubectl get pods -oyaml` and share the pod manifest?

**Comment by ZiedBenSaber** [comment] 2022-02-28 09:20
@ChunyiLyu Thanks you for your answer.
Here's one of the statefulset replica's yaml that has been deployed with the config I posted in the first comment :
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2022-02-15T11:33:44+01:00"
    prometheus.io/port: "15692"
    prometheus.io/scrape: "true"
    rabbitmq.com/lastRestartAt: "2022-01-12T12:32:33Z"
  creationTimestamp: "2022-02-23T17:53:17Z"
  generateName: rabbitmq-cluster-server-
  labels:
    app.kubernetes.io/component: rabbitmq
    app.kubernetes.io/name: rabbitmq-cluster
    app.kubernetes.io/part-of: rabbitmq
    controller-revision-hash: rabbitmq-cluster-server-54857ddbcd
    statefulset.kubernetes.io/pod-name: rabbitmq-cluster-server-0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/restartedAt: {}
          f:prometheus.io/port: {}
          f:prometheus.io/scrape: {}
          f:rabbitmq.com/lastRestartAt: {}
        f:generateName: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/component: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/part-of: {}
          f:controller-revision-hash: {}
          f:statefulset.kubernetes.io/pod-name: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"70fdbc6f-2a01-45cd-84ad-3f1e03322791"}: {}
      f:spec:
        f:affinity:
          .: {}
          f:podAntiAffinity:
            .: {}
            f:preferredDuringSchedulingIgnoredDuringExecution: {}
        f:automountServiceAccountToken: {}
        f:containers:
          k:{"name":"rabbitmq"}:
            .: {}
            f:env:
              .: {}
              k:{"name":"K8S_HOSTNAME_SUFFIX"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"K8S_SERVICE_NAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"MY_POD_NAME"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"MY_POD_NAMESPACE"}:
                .: {}
                f:name: {}
                f:valueFrom:
                  .: {}
                  f:fieldRef: {}
              k:{"name":"RABBITMQ_ENABLED_PLUGINS_FILE"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"RABBITMQ_NODENAME"}:
                .: {}
                f:name: {}
                f:value: {}
              k:{"name":"RABBITMQ_USE_LONGNAME"}:
                .: {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:lifecycle:
              .: {}
              f:preStop:
                .: {}
                f:exec:
                  .: {}
                  f:command: {}
            f:name: {}
            f:ports:
              .: {}
              k:{"containerPort":4369,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":5672,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":15672,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":15692,"protocol":"TCP"}:
                .: {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              .: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:tcpSocket:
                .: {}
                f:port: {}
              f:timeoutSeconds: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/etc/pod-info/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/etc/rabbitmq/conf.d/10-operatorDefaults.conf"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:subPath: {}
              k:{"mountPath":"/etc/rabbitmq/conf.d/11-default_user.conf"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:subPath: {}
              k:{"mountPath":"/etc/rabbitmq/conf.d/90-userDefinedConfiguration.conf"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:subPath: {}
              k:{"mountPath":"/federation/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/operator"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/lib/rabbitmq/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/lib/rabbitmq/mnesia/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:hostname: {}
        f:imagePullSecrets:
          .: {}
          k:{"name":"dummy-registry"}: {}
        f:initContainers:
          .: {}
          k:{"name":"setup-container"}:
            .: {}
            f:command: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
            f:volumeMounts:
              .: {}
              k:{"mountPath":"/operator"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/tmp/default_user.conf"}:
                .: {}
                f:mountPath: {}
                f:name: {}
                f:subPath: {}
              k:{"mountPath":"/tmp/erlang-cookie-secret/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/tmp/rabbitmq-plugins/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/lib/rabbitmq/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
              k:{"mountPath":"/var/lib/rabbitmq/mnesia/"}:
                .: {}
                f:mountPath: {}
                f:name: {}
        f:nodeSelector: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext:
          .: {}
          f:fsGroup: {}
          f:runAsUser: {}
        f:serviceAccount: {}
        f:serviceAccountName: {}
        f:subdomain: {}
        f:terminationGracePeriodSeconds: {}
        f:topologySpreadConstraints:
          .: {}
          k:{"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"ScheduleAnyway"}:
            .: {}
            f:labelSelector: {}
            f:maxSkew: {}
            f:topologyKey: {}
            f:whenUnsatisfiable: {}
        f:volumes:
          .: {}
          k:{"name":"definitions"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:secretName: {}
          k:{"name":"erlang-cookie-secret"}:
            .: {}
            f:name: {}
            f:secret:
              .: {}
              f:defaultMode: {}
              f:secretName: {}
          k:{"name":"persistence"}:
            .: {}
            f:name: {}
            f:persistentVolumeClaim:
              .: {}
              f:claimName: {}
          k:{"name":"plugins-conf"}:
            .: {}
            f:configMap:
              .: {}
              f:defaultMode: {}
              f:name: {}
            f:name: {}
          k:{"name":"pod-info"}:
            .: {}
            f:downwardAPI:
              .: {}
              f:defaultMode: {}
              f:items: {}
            f:name: {}
          k:{"name":"rabbitmq-confd"}:
            .: {}
            f:name: {}
            f:projected:
              .: {}
              f:defaultMode: {}
              f:sources: {}
          k:{"name":"rabbitmq-erlang-cookie"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
          k:{"name":"rabbitmq-plugins"}:
            .: {}
            f:emptyDir: {}
            f:name: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-02-23T17:53:17Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:initContainerStatuses: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"100.64.1.171"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: Go-http-client
    operation: Update
    subresource: status
    time: "2022-02-23T17:53:47Z"
  name: rabbitmq-cluster-server-0
  namespace: lbc
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: rabbitmq-cluster-server
    uid: 70fdbc6f-2a01-45cd-84ad-3f1e03322791
  resourceVersion: "17786418350"
  uid: c11cbb9a-cc25-4e2b-b07f-26256a0509d8
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - rabbitmq-cluster
          topologyKey: kubernetes.io/hostname
        weight: 100
  automountServiceAccountToken: true
  containers:
  - env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: K8S_SERVICE_NAME
      value: rabbitmq-cluster-nodes
    - name: RABBITMQ_ENABLED_PLUGINS_FILE
      value: /operator/enabled_plugins
    - name: RABBITMQ_USE_LONGNAME
      value: "true"
    - name: RABBITMQ_NODENAME
      value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE)
    - name: K8S_HOSTNAME_SUFFIX
      value: .$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE)
    image: docker.registry.company/rabbitmq:3.9.8-management
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/bash
          - -c
          - if [ ! -z "$(cat /etc/pod-info/skipPreStopChecks)" ]; then exit 0; fi;
            rabbitmq-upgrade await_online_quorum_plus_one -t 604800; rabbitmq-upgrade
            await_online_synchronized_mirror -t 604800; rabbitmq-upgrade drain -t
            604800
    name: rabbitmq
    ports:
    - containerPort: 4369
      name: epmd
      protocol: TCP
    - containerPort: 5672
      name: amqp
      protocol: TCP
    - containerPort: 15672
      name: management
      protocol: TCP
    - containerPort: 15692
      name: prometheus
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: amqp
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "2"
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 300Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/rabbitmq/
      name: rabbitmq-erlang-cookie
    - mountPath: /var/lib/rabbitmq/mnesia/
      name: persistence
    - mountPath: /federation/
      name: definitions
    - mountPath: /operator
      name: rabbitmq-plugins
    - mountPath: /etc/rabbitmq/conf.d/10-operatorDefaults.conf
      name: rabbitmq-confd
      subPath: operatorDefaults.conf
    - mountPath: /etc/rabbitmq/conf.d/90-userDefinedConfiguration.conf
      name: rabbitmq-confd
      subPath: userDefinedConfiguration.conf
    - mountPath: /etc/pod-info/
      name: pod-info
    - mountPath: /etc/rabbitmq/conf.d/11-default_user.conf
      name: rabbitmq-confd
      subPath: default_user.conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6xtcx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: rabbitmq-cluster-server-0
  imagePullSecrets:
  - name: dummy-registry
  initContainers:
  - command:
    - sh
    - -c
    - cp /tmp/erlang-cookie-secret/.erlang.cookie /var/lib/rabbitmq/.erlang.cookie
      && chmod 600 /var/lib/rabbitmq/.erlang.cookie ; cp /tmp/rabbitmq-plugins/enabled_plugins
      /operator/enabled_plugins ; echo '[default]' > /var/lib/rabbitmq/.rabbitmqadmin.conf
      && sed -e 's/default_user/username/' -e 's/default_pass/password/' /tmp/default_user.conf
      >> /var/lib/rabbitmq/.rabbitmqadmin.conf && chmod 600 /var/lib/rabbitmq/.rabbitmqadmin.conf
    image: docker.registry.company/rabbitmq:3.9.8-management
    imagePullPolicy: IfNotPresent
    name: setup-container
    resources:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 500Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/rabbitmq-plugins/
      name: plugins-conf
    - mountPath: /var/lib/rabbitmq/
      name: rabbitmq-erlang-cookie
    - mountPath: /tmp/erlang-cookie-secret/
      name: erlang-cookie-secret
    - mountPath: /operator
      name: rabbitmq-plugins
    - mountPath: /var/lib/rabbitmq/mnesia/
      name: persistence
    - mountPath: /tmp/default_user.conf
      name: rabbitmq-confd
      subPath: default_user.conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-6xtcx
      readOnly: true
  nodeName: scw-k8s-lbc-infratest-services-93f8147bc0b5440
  nodeSelector:
    k8s.scaleway.com/pool-name: services
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 999
    runAsUser: 999
  serviceAccount: rabbitmq-cluster-server
  serviceAccountName: rabbitmq-cluster-server
  subdomain: rabbitmq-cluster-nodes
  terminationGracePeriodSeconds: 604800
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        app.kubernetes.io/name: rabbitmq-cluster
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  volumes:
  - name: persistence
    persistentVolumeClaim:
      claimName: persistence-rabbitmq-cluster-server-0
  - name: definitions
    secret:
      defaultMode: 420
      secretName: rabbitmq-definitions
  - configMap:
      defaultMode: 420
      name: rabbitmq-cluster-plugins-conf
    name: plugins-conf
  - name: rabbitmq-confd
    projected:
      defaultMode: 420
      sources:
      - configMap:
          items:
          - key: operatorDefaults.conf
            path: operatorDefaults.conf
          - key: userDefinedConfiguration.conf
            path: userDefinedConfiguration.conf
          name: rabbitmq-cluster-server-conf
      - secret:
          items:
          - key: default_user.conf
            path: default_user.conf
          name: rabbitmq-cluster-default-user
  - emptyDir: {}
    name: rabbitmq-erlang-cookie
  - name: erlang-cookie-secret
    secret:
      defaultMode: 420
      secretName: rabbitmq-cluster-erlang-cookie
  - emptyDir: {}
    name: rabbitmq-plugins
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels['skipPreStopChecks']
        path: skipPreStopChecks
    name: pod-info
  - name: kube-api-access-6xtcx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-23T17:53:28Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-23T17:53:47Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-23T17:53:47Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-23T17:53:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e1f57db3c55e2059598fb65662fe68eea796743715e43a7b1eeb24d8cbbdb927
    image: docker.io/library/rabbitmq:3.9.8-management
    imageID: docker.io/library/rabbitmq@sha256:3af5bad90996762e5a2fedfbffd59a0a13da86b6a3748add4ba7996b849545d8
    lastState: {}
    name: rabbitmq
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-02-23T17:53:28Z"
  hostIP: 10.197.74.5
  initContainerStatuses:
  - containerID: containerd://7ee7a6a357dc5eb15a77e566ee0be047ec13313bc662a63216bcf4bc9731c671
    image: docker.io/library/rabbitmq:3.9.8-management
    imageID: docker.io/library/rabbitmq@sha256:3af5bad90996762e5a2fedfbffd59a0a13da86b6a3748add4ba7996b849545d8
    lastState: {}
    name: setup-container
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://7ee7a6a357dc5eb15a77e566ee0be047ec13313bc662a63216bcf4bc9731c671
        exitCode: 0
        finishedAt: "2022-02-23T17:53:27Z"
        reason: Completed
        startedAt: "2022-02-23T17:53:27Z"
  phase: Running
  podIP: 100.64.1.171
  podIPs:
  - ip: 100.64.1.171
  qosClass: Burstable
  startTime: "2022-02-23T17:53:17Z"
  ```

**Comment by coro** [comment] 2022-03-30 10:45
Looks like we can't reproduce this. If you're still seeing issues, it would be good to know if they persist after recreating the statefulset. Otherwise, I'm closing this issue, please feel free to reopen if the issue persists.

**Closed by coro** 2022-03-30 10:45 UTC
Labels: question
