### ISSUE TITLE
Allow user to configure the cluster default user 

### ISSUE THREAD

**Issue by yaronp68** [rabbitmq/cluster-operator#458] opened 2020-11-10 12:08 UTC
As an operator user when I create a cluster, I currently can't configure the credentials for the RMQ default user

This issue is about adding the properties needed for configuring the default RMQ credentials

This will enable different instances created by the operator to have different default users

**Comment by mkuratczyk** [comment] 2020-11-10 13:44
The last sentence is inaccurate. Each cluster has different credentials already. I just deployed 2 clusters using the `hello-world` example and I can see different credentials:
```
$ kubectl rabbitmq secrets hello-world
username: Vc8RBHpV287cM50NYaXJqRsCmKci7oql
password: fys0JOI5LH6ZrbNkLBdIMA4xFrOLBMoh
$ kubectl rabbitmq secrets hello-world2
username: -ZOIfPgprZqSAYodxr-baRWuRtU6fzdQ
password: oJuRMiCqq0GCmmHCWipr-d5g8P-nB_Bg
```

As I understand, the goal is for these credentials to be known upfront. I see 2 options:
1. Default user secret could be created first and the operator would not overwrite it. If the user wants some specific credentials to be used, they would run `kubectl create secret ...` and only then `kubectl create rabbitmqcluster ...`
2. We could add CRD properties but we shouldn't store them in the CR. The operator would just pass the values to the secret and remove them from the CR definition.

**Comment by Zerpet** [comment] 2020-11-10 14:41
I think this is a duplicate of #310 ?

**Closed** 2020-11-10 16:38 UTC
Labels: duplicate
