### ISSUE TITLE
after updating cluster operator error "failed calling webhook "vvhost.kb.io": failed to call webhook:"

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [rabbitmq/cluster-operator#1255] opened 2023-02-04 23:14 UTC
## Describe the bug
I had some vhosts installed before, but after updating I get following errors:

```
cannot patch "vhost" with kind Vhost: Internal error occurred: failed calling webhook "vvhost.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator.rabbitmq-cluster-operator.svc:443/validate-rabbitmq-com-v1beta1-vhost?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "rmq-msg-topology-ca")
upgrade.go:434: [debug] warning: Upgrade "flavewksball22" failed: cannot patch "vhost" with kind Vhost: Internal error occurred: failed calling webhook "vvhost.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator.rabbitmq-cluster-operator.svc:443/validate-rabbitmq-com-v1beta1-vhost?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "rmq-msg-topology-ca")
Error: UPGRADE FAILED: cannot patch "vhost" with kind Vhost: Internal error occurred: failed calling webhook "vvhost.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator.rabbitmq-cluster-operator.svc:443/validate-rabbitmq-com-v1beta1-vhost?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "rmq-msg-topology-ca")
helm.go:84: [debug] cannot patch "vhost" with kind Vhost: Internal error occurred: failed calling webhook "vvhost.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator.rabbitmq-cluster-operator.svc:443/validate-rabbitmq-com-v1beta1-vhost?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "rmq-msg-topology-ca")
helm.sh/helm/v3/pkg/kube.(*Client).Update
	helm.sh/helm/v3/pkg/kube/client.go:274
helm.sh/helm/v3/pkg/action.(*Upgrade).releasingUpgrade
	helm.sh/helm/v3/pkg/action/upgrade.go:376
runtime.goexit
	runtime/asm_arm64.s:1172
```

## To Reproduce
Update to the latest version

Include any YAML or manifest necessary to reproduce the problem.

**Expected behavior**

## Version and environment information
- RabbitMQ: 3.10.13
- RabbitMQ Cluster Operator: 3.2.2
- Kubernetes: 1.23.14
- Cloud provider or hardware configuration:

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-02-04 23:21
Seems like it has something to do with an older kubernetes version (see same error here https://github.com/minio/operator/issues/942)

After downgrading to version 3.2.0 it works again?

**Comment by DanielePalaia** [comment] 2023-02-06 10:31
Hi @h0jeZvgoxFepBQ2C 

When you say RabbitMQ Cluster Operator: 3.2.2 you mean the bitnami package version?
Are you deploying on Openshift?

From which version to what version are you upgrading?

Can you try to see if you can reproduce the issue using the official installation manifests (as described  in this github readme page?)

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-02-06 12:36
> When you say RabbitMQ Cluster Operator: 3.2.2 you mean the bitnami package version?
Yes, sorry for not mentioning it, yes the helm chart from bitnami

> From which version to what version are you upgrading?

**Comment by DanielePalaia** [comment] 2023-02-06 13:19
@h0jeZvgoxFepBQ2C Another thing I forgot mentioning. It seems like the issue is related to the messaging topology operator (https://github.com/rabbitmq/messaging-topology-operator) which is using the cert-mager to deploy and manage certificates. Can you check that this component is installed and all pods are up and running?

**Comment by spencer-nicol** [comment] 2023-02-08 19:10
I'm also running into this issue after a fresh deployment, any update from the message-topology-operator causes this. 

```
Error from server (InternalError): error when creating "k8s/overlays/test": Internal error occurred: failed calling webhook "vpermission.kb.io": failed to call webhook: Post "https://webhook-service.rabbitmq-system.svc:443/validate-rabbitmq-com-v1beta1-permission?timeout=10s": context deadline exceeded
Error from server (InternalError): error when creating "k8s/overlays/test": Internal error occurred: failed calling webhook "vuser.kb.io": failed to call webhook: Post "https://webhook-service.rabbitmq-system.svc:443/validate-rabbitmq-com-v1beta1-user?timeout=10s": context deadline exceeded
Error from server (InternalError): error when creating "k8s/overlays/test": Internal error occurred: failed calling webhook "vvhost.kb.io": failed to call webhook: Post "https://webhook-service.rabbitmq-system.svc:443/validate-rabbitmq-com-v1beta1-vhost?timeout=10s": context deadline exceeded
```

Kubernetes:
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.23.14-gke.1800

Deployed on GKE.

Cert-manager version: v1.8.1 and all certificates are valid.

**Comment by DanielePalaia** [comment] 2023-02-09 10:25
Hi @spencer-nicol From which version to which version of the messaging operator or helm chart are you upgrading? Are you also using helm like @h0jeZvgoxFepBQ2C ?

I made a few tests. I tried to install with helm from version 3.2.0 and then upgrade to 3.2.2 and I'm not having issues.
I also tried to do an installation from the manifest at version 1.9.0 of the messaging operator to the last 1.10.1 and I'm also not able to reproduce the issue.

**Comment by spencer-nicol** [comment] 2023-02-09 13:55
I performed the steps as follows:
---
* Installed cert-manager: `kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml`
* Installed the cluster operator: `kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/v2.1.0/download/cluster-operator.yml`
* Installed the message topology operator: `kubectl apply -f https://github.com/rabbitmq/messaging-topology-operator/releases/v1.10.1/download/messaging-topology-operator-with-certmanager.yaml
* created a secret "rabbitmq" for external admin secret as defined in the [docs](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/external-admin-secret-credentials)
* Deployed the cluster (redacting for brevity): 
  ```
    apiVersion: ...
    metadata:
      name: rabbitmq
      namespace: <my_namespace>
      annotations:
        rabbitmq.com/topology-allowed-namespaces: "<my_namespace>,rabbitmq-system"
    spec:
      ...
      secretBackend:
        externalSecret:
          name: "rabbitmq"
    ...
  ```
* Attempting to add users and vhost as defined in message-topology-operator docs:
  * Secret for user in <my_namespace>
  * Vhost in <my_namespace>:
    ```
    apiVersion: ...
    spec:
      name: "/new-vhost"
      rabbitmqClusterReference:
        name: rabbitmq
    ```
  * User and Permissions redacted for brevity.
---
Could this be caused by the external admin credentials?

**Comment by DanielePalaia** [comment] 2023-02-09 14:46
@spencer-nicol Thank you for your input but unfortunately I can't still reproduce this.

I started from a clean installation and basically I followed up your step. I created a RabbitMQ cluster specifying an external secret and I created a new User and Vhost with the messaging topology operator.

  Type    Reason             Age                    From              Message
  ----    ------             ----                   ----              -------
  Normal  SuccessfulDeclare  5m59s (x2 over 5m59s)  vhost-controller  Successfully declare vhost

I can see the vhost in the UI as well.
Did you create the secret in the same format specified on the guideline with default_user.conf, host, password, port ecc?
Are you sure that the credentials you put in default_user.conf are the same in username and password?

**Comment by spencer-nicol** [comment] 2023-02-09 16:51
@DanielePalaia I retrieved the logs from message-topology-operator. This is the logs immediately following an apply to the vhost, user, and permissions creation.

```
2023/02/08 22:29:32 http: TLS handshake error from 198.18.114.2:39118: local error: tls: bad record MAC
{"level":"error","ts":"2023-02-08T22:30:40Z","logger":"controller-runtime.webhook.webhooks","msg":"unable to process a request with an unknown content type","webhook":"/validate-rabbitmq-com-v1beta1-vhost","content type":"","error":"contentType=, expected application/json","stacktrace":"sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/webhook/admission/http.go:72\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:60\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:146\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:108\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2487\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.initALPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3556\nnet/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5910"}
{"level":"error","ts":"2023-02-08T23:05:34Z","logger":"controller-runtime.webhook.webhooks","msg":"unable to process a request with an unknown content type","webhook":"/validate-rabbitmq-com-v1beta1-vhost","content type":"","error":"contentType=, expected application/json","stacktrace":"sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.2/pkg/webhook/admission/http.go:72\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:60\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:146\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\ngithub.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2\n\t/go/pkg/mod/github.com/prometheus/client_golang@v1.14.0/prometheus/promhttp/instrument_server.go:108\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2487\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.initALPNRequest.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:3556\nnet/http.(*http2serverConn).runHandler\n\t/usr/local/go/src/net/http/h2_bundle.go:5910"}
2023/02/08 23:06:06 http: TLS handshake error from 198.18.114.2:55576: local error: tls: bad record MAC
```

This is from the GKE cluster.

**Comment by DanielePalaia** [comment] 2023-02-09 17:17
@spencer-nicol Well not sure why this is happening to you. The errors seems related to TLS or certificates.

I'm noticing that the only differences between my tests and your tests seem to be the cert manager version. I'm using the last one while you are using the not very recent 1.8. 
Maybe can you try to reinstall and upgrade it?

I'm also testing on GKE Kubernetes 1.23.15

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-02-10 10:22
Ok so I tried it now again with our testing cluster and I get the same error again when I upgrade to 3.2.2 from 3.2.0 and deploying an application which has a vhost included.

![Bildschirm­foto 2023-02-10 um 11 21 36](https://user-images.githubusercontent.com/10075/218067519-58b2d45a-211d-4c4f-ba9d-482772b4fc6e.png)

I'm not sure why the certificates change at all?

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-02-10 10:23
![Bildschirm­foto 2023-02-10 um 11 23 01](https://user-images.githubusercontent.com/10075/218067820-255e4d59-3f01-4091-815d-bc01f5dc059b.png)

```
cannot patch "vhost" with kind Vhost: Internal error occurred: failed calling webhook "vvhost.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator.rabbitmq-cluster-operator.svc:443/validate-rabbitmq-com-v1beta1-vhost?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "rmq-msg-topology-ca")
upgrade.go:436: [debug] warning: Upgrade "flavetest23" failed: cannot patch "vhost" with kind Vhost: Internal error occurred: failed calling webhook "vvhost.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator.rabbitmq-cluster-operator.svc:443/validate-rabbitmq-com-v1beta1-vhost?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "rmq-msg-topology-ca")
Error: UPGRADE FAILED: cannot patch "vhost" with kind Vhost: Internal error occurred: failed calling webhook "vvhost.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator.rabbitmq-cluster-operator.svc:443/validate-rabbitmq-com-v1beta1-vhost?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "rmq-msg-topology-ca")
helm.go:84: [debug] cannot patch "vhost" with kind Vhost: Internal error occurred: failed calling webhook "vvhost.kb.io": failed to call webhook: Post "https://rabbitmq-cluster-operator-rabbitmq-messaging-topology-operator.rabbitmq-cluster-operator.svc:443/validate-rabbitmq-com-v1beta1-vhost?timeout=10s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "rmq-msg-topology-ca")
```

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-02-10 10:29
It seems that the error happens in release 3.2.1. Downgrading to 3.2.0 and everything worked fine, upgrading to 3.2.1 failed again.

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-02-10 10:29
Ah yeah, I'm using the helm chart btw :)

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-02-10 13:18
It also seems that the caBundle entries are changed during each deployement, even when no configuration options changed?

![Bildschirm­foto 2023-02-10 um 14 18 20](https://user-images.githubusercontent.com/10075/218101662-f3586418-9358-4131-a415-5a4a22e8ba81.png)

**Comment by DanielePalaia** [comment] 2023-02-12 16:19
Hi @h0jeZvgoxFepBQ2C I tried to do some few testings but still I failed to reproduce this issue even using the helm chart.

What I did was:

```
dpalaia@dpalaiaYMD6R cluster-operator % helm install my-release bitnami/rabbitmq-cluster-operator --version 3.2.0
NAME: my-release
LAST DEPLOYED: Sun Feb 12 15:33:33 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
CHART NAME: rabbitmq-cluster-operator
CHART VERSION: 3.2.0
APP VERSION: 2.1.0
```

I was able to see that the images of the operators were these ones:
```
docker.io/bitnami/rabbitmq-cluster-operator:2.1.0-scratch-r0
```
and
```
docker.io/bitnami/rmq-messaging-topology-operator:1.10.0-scratch-r0
```

I created a namespace rabbitmq-system I created a simple rabbitmq-cluster that was up and running.
With the messaging-topology operator I created a vhost and a queue.
I was able in the UI to see the vhost and the queue correctly created.
I put some messages on the queue as well.

I then upgraded the operators so I made a 

```
dpalaia@dpalaiaYMD6R cluster-operator % helm upgrade my-release bitnami/rabbitmq-cluster-operator
Release "my-release" has been upgraded. Happy Helming!
NAME: my-release
LAST DEPLOYED: Sun Feb 12 15:41:22 2023
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
CHART NAME: rabbitmq-cluster-operator
CHART VERSION: 3.2.2
APP VERSION: 2.1.0
```

These were the images:

```
docker.io/bitnami/rabbitmq-cluster-operator:2.1.0-scratch-r3

docker.io/bitnami/rmq-messaging-topology-operator:1.10.0-scratch-r1
```
The images seems different but the seem to be based on the same operators releases(cluster operator 2.1.0 and messaging operator 1.10).

I didn`t receive any issue during the upgrade and I was able to continue working with the cluster.
I also made a few rolling update of the rabbitmq-cluster over time without receiving any issues.

It maybe be something dependent on your configuration.

1) What Kubernetes version are you using? I tested with GKE but it's not clear if you are using Openshift or not
2) Are you relying on cert-manager to generate certificates for the webhooks? 
3) Are you using some specific functionality? Is it possible to have a look to your rabbitmqcluster manifest?

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-02-14 12:11
> What Kubernetes version are you using? I tested with GKE but it's not clear if you are using Openshift or not

We are using the managed Digital Ocean Kubernetes service, version: 1.23.14-do.0


> Are you relying on cert-manager to generate certificates for the webhooks?

Yeah, we are using cert-manager for our certificates (v.1.11.0).

> Are you using some specific functionality? Is it possible to have a look to your rabbitmqcluster manifest?

We are using webstomp and oauth authentication (for connections, not for management ui)

```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
  namespace: rabbitmq-cluster
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "*"
spec:
  replicas: 5
  persistence:
    storage: "30Gi"
  rabbitmq:
    additionalPlugins:
      - rabbitmq_web_stomp
      - rabbitmq_auth_backend_oauth2
    additionalConfig: |
      log.console = true
      log.console.level = debug
      auth_backends.1 = oauth2
      auth_backends.2 = internal

      cluster_partition_handling = pause_minority

      auth_oauth2.resource_server_type = rabbitmq
      auth_oauth2.resource_server_id = rabbitmq-cluster

      web_stomp.ws_frame = binary
      # vm_memory_high_watermark.relative = 0.8

    advancedConfig: |
      [
        {rabbit, [
          {auth_backends, [rabbit_auth_backend_oauth2, rabbit_auth_backend_internal]}
        ]},
        {rabbitmq_management, [
          {enable_uaa, false},
          {oauth_enabled, false}
        ]},
        {rabbitmq_auth_backend_oauth2, [
          {resource_server_id, <<"rabbitmq-cluster">>},
          {resource_server_type, <<"rabbitmq">>},
          
          {key_config, [
            {default_key, <<"key1">>},
            {signing_keys, #{
              <<"key1">> => {pem, <<"-----BEGIN PUBLIC KEY-----
              .....
      -----END PUBLIC KEY-----">>}
              }}
          ]}
        ]}
      ].


  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: rabbitmq-cluster
          topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: "1"
      memory: 3Gi
    limits:
      #cpu: 800m
      memory: 3Gi

```

> Are you creating the objects with the messaging operator on the same k8s namespace where the cluster is deployed?

No, the rabbitmq-cluster is running in the namespace ```rabbitmq-cluster``` but our applications reside in their own namespaces. For this we create external services like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-cluster
  namespace: {{ .Release.Name }}
spec:
  type: ExternalName
  externalName: rabbitmq-cluster.rabbitmq-cluster.svc.cluster.local
```

Connection authentication works via JWT token (works totally fine).

**Comment by cortex3** [comment] 2023-02-15 18:28
same here, using default values and kubernetes 1.20

**Comment by DanielePalaia** [comment] 2023-02-16 11:37
Hi all. It seems like an issue on the bitnami installation chart. We don't directly support the chart but it seems something related on a new modification recently done https://github.com/bitnami/charts/commit/d8da225bdab70026763a8077e4f103295ecb7ea7

I contacted my colleagues from Bitnami team and opened an issue there: https://github.com/bitnami/charts/issues/14908

We can maybe continue the discussion there.

**Comment by DanielePalaia** [comment] 2023-02-16 11:57
It seems like Bitnami fixed the issue already https://github.com/bitnami/charts/pull/14909. Closing this one

**Comment by DanielePalaia** [comment] 2023-02-16 11:58
and @h0jeZvgoxFepBQ2C thank you to have reported this!

**Closed by DanielePalaia** 2023-02-16 11:57 UTC
Labels: bug

**Comment by migruiz4** [comment] 2023-02-16 12:40
Hi there!

We have just released version 3.2.3 of the `bitnami/rabbitmq-cluster-operator` chart. 
Could you please try upgrading the chart and confirm if this issue is fixed?

**Comment by h0jeZvgoxFepBQ2C** [comment] 2023-02-20 12:27
Yes, worked fine, thank you so much! ❤️

**Comment by migruiz4** [comment] 2023-03-29 13:03
Hi @davidbugi,

Could you please open a new issue in https://github.com/bitnami/charts?
There we can give you better assistance with issues related to the `bitnami/rabbitmq-cluster-operator` chart.

Please make sure to fill the issue template with any information that may be helpful for us to reproduce your case.

**Comment by davidbugi** [comment] 2023-03-29 13:19
Will do, thank you @migruiz4
